### ISSUE TITLE
你的文章没有给原作者链接，仓库脚本 直接改了Author -_-!

### ISSUE THREAD

**Issue by oldratlee** [Lawrence-zxc/usefull-develop-tools#1]
原仓库 https://github.com/oldratlee/useful-scripts 是 [Apache v2协议](https://www.apache.org/licenses/LICENSE-2.0.html)，你可以使用的。
![image](https://user-images.githubusercontent.com/1063891/31314565-2b193eba-abc9-11e7-8223-697fd640d157.png)

但是

# 1 你的文章 没有附上 源链接和原作者署名信息 

文章  https://lawrence-zxc.github.io/2012/07/10/show-busy-java-threads/ 直接是 原作者的文档和代码，但 **没有**附上 源链接。
\# 原作者的文档 https://github.com/oldratlee/useful-scripts/blob/master/docs/java.md#beer-show-busy-java-threadssh

PS: 你自己文章 **也是**要求了『保持署名』的哦：
![image](https://user-images.githubusercontent.com/1063891/31314516-72895718-abc8-11e7-8a1b-2c49de774db0.png)
\#  [Apache v2协议](https://www.apache.org/licenses/LICENSE-2.0.html) 并不限制 『演绎』、『商用』。

# 2 你的脚本源码中直接把Author也改成自己了

https://github.com/Lawrence-zxc/usefull-develop-tools/blob/master/my_usefull_script/shell/show-busy-java-threads.sh ：
![image](https://user-images.githubusercontent.com/1063891/31133930-6db5c104-a826-11e7-93cd-09b43437a8ed.png)

这个脚本拷贝到你的仓库中可以，保留Author并提供 源链接还是 必要的 ～
\# 源链接 https://github.com/oldratlee/useful-scripts/blob/master/show-busy-java-threads.sh

# PS

1. 说个笑，最近国内 常常爆出 抄袭的事，不怕被人肉？ 😸 
2. 这段时间有不少更新，可以看看
    -  支持输出到文件，方便记录以回溯查看
    - 支持指定 `jstack` 路径，对于`sudo`的情况，`jstack`往往不能自动找到
    - 支持 `-F` 选项， force jstack
    - 支持多次输出
    - 详见文档 https://github.com/oldratlee/useful-scripts/blob/master/docs/java.md#beer-show-busy-java-threadssh
3. 仓库名有个拼写错，`usefull-develop-tools`的`usefull`多了个`l`，应该是`useful`

**Comment by wanghuizi** [comment]
好的, 我有空改一下




------------------ 原始邮件 ------------------
发件人: "李鼎(哲良)";<notifications@github.com>;
发送时间: 2017年10月3日(星期二) 晚上11:38
收件人: "Lawrence-zxc/usefull-develop-tools"<usefull-develop-tools@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [Lawrence-zxc/usefull-develop-tools] 你的文章没有给原作者链接，仓库脚本 直接改了Author -_-! (#1)




1
 
文章  https://lawrence-zxc.github.io/2012/07/10/show-busy-java-threads/ 直接是 原作者的文档和代码，完全没有附上 源链接。
 # 原作者的文档 https://github.com/oldratlee/useful-scripts/blob/master/docs/java.md#beer-show-busy-java-threadssh
 
2
 
脚本中直接把Author也改成自己了
 https://github.com/Lawrence-zxc/usefull-develop-tools/blob/master/my_usefull_script/shell/show-busy-java-threads.sh ：
 
 
这个脚本拷贝到你的仓库中可以，保留Author并提供 源链接还是 必要的 ～
 # 源链接 https://github.com/oldratlee/useful-scripts/blob/master/show-busy-java-threads.sh
 
PS
 
说个笑，最近国内 常常爆出 抄袭的事，不怕被人肉？ 😸

**Comment by oldratlee** [comment]
@Lawrence-zxc 看到脚本的这项已经改了，附上了源链接  👍 

但`@author`删除了，要保留 `@author` 。

![image](https://user-images.githubusercontent.com/1063891/31325861-74ce757a-ac87-11e7-9d38-b4c9a59eb641.png)

另外， 文章这项还没有改，加上文章内容来自的 『文档源链接』，但你已经把Issue关了 😂 

# PS

看了一下你的博客，其中 命令可能有问题，`base64`命令有的是 `-d` 小d选项： 😃 （当然你可能是有意的，更hacker）

![image](https://user-images.githubusercontent.com/1063891/31325963-65a6b412-ac88-11e7-9563-4579b366fe04.png)

```bash
$echo 'aHR0cDovL2xhd3JlbmNlLXp4Yy5naXRodWIuaW8vaW1nL015RGVlckNWLnBkZg==' | base64 -D
base64: invalid option -- 'D'
Try `base64 --help' for more information.

$echo 'aHR0cDovL2xhd3JlbmNlLXp4Yy5naXRodWIuaW8vaW1nL015RGVlckNWLnBkZg==' | base64 -d
http://lawrence-zxc.github.io/img/MyDeerCV.pdf
```
